#!/bin/bash

if [ ! -f simulator_installed.txt  ]; then 
 
	sudo apt-get update
	sudo apt-get install xterm
	sudo apt-get install blender 
	
	sudo apt-get install gcc
	sudo apt-get install git
	sudo apt-get install make

	git clone https://github.com/memristor/pic-motion-driver
	git clone https://github.com/memristor/mep2
	
	sudo chmod u+x run_pic
		
	touch simulator_installed.txt
	fi
 
       	 

	sudo xterm -e ./run_pic & 
	cd mep2 
	xterm -e ./run_blender &
